package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	stepsecurityapi "github.com/step-security/terraform-provider-stepsecurity/internal/stepsecurity-api"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                   = &developerMDMIDEExtensionPolicyResource{}
	_ resource.ResourceWithConfigure      = &developerMDMIDEExtensionPolicyResource{}
	_ resource.ResourceWithValidateConfig = &developerMDMIDEExtensionPolicyResource{}
	_ resource.ResourceWithImportState    = &developerMDMIDEExtensionPolicyResource{}
)

// Identifier and version shapes mirrored from backend validation.
const (
	developerMDMIdentifierPattern = `^[A-Za-z0-9][A-Za-z0-9-]*$`
	developerMDMVersionPattern    = `^\d+\.\d+\.\d+(@[A-Za-z0-9._-]+)?$`
)

var (
	developerMDMIdentifierRegex = regexp.MustCompile(developerMDMIdentifierPattern)
	developerMDMVersionRegex    = regexp.MustCompile(developerMDMVersionPattern)
)

// NewDeveloperMDMIDEExtensionPolicyResource is a helper function to simplify the provider implementation.
func NewDeveloperMDMIDEExtensionPolicyResource() resource.Resource {
	return &developerMDMIDEExtensionPolicyResource{}
}

// developerMDMIDEExtensionPolicyResource is the resource implementation.
type developerMDMIDEExtensionPolicyResource struct {
	client stepsecurityapi.Client
}

// developerMDMIDEExtensionPolicyModel maps the resource schema data.
type developerMDMIDEExtensionPolicyModel struct {
	ID          types.String                        `tfsdk:"id"`
	PolicyID    types.String                        `tfsdk:"policy_id"`
	Name        types.String                        `tfsdk:"name"`
	Description types.String                        `tfsdk:"description"`
	Target      types.String                        `tfsdk:"target"`
	Mode        types.String                        `tfsdk:"mode"`
	Rules       []developerMDMIDEExtensionRuleModel `tfsdk:"rules"`
	CreatedBy   types.String                        `tfsdk:"created_by"`
	CreatedAt   types.String                        `tfsdk:"created_at"`
	UpdatedBy   types.String                        `tfsdk:"updated_by"`
	UpdatedAt   types.String                        `tfsdk:"updated_at"`
}

// developerMDMIDEExtensionRuleModel maps a single allow/block rule.
type developerMDMIDEExtensionRuleModel struct {
	Publisher types.String `tfsdk:"publisher"`
	Name      types.String `tfsdk:"name"`
	Versions  types.Set    `tfsdk:"versions"`
	Stable    types.Bool   `tfsdk:"stable"`
}

// Metadata returns the resource type name.
func (r *developerMDMIDEExtensionPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_developer_mdm_ide_extension_policy"
}

// Schema defines the schema for the resource.
func (r *developerMDMIDEExtensionPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Developer MDM VS Code IDE extension policy in StepSecurity. " +
			"The policy authors allow/block intent; StepSecurity compiles and enforces it. " +
			"Policy identity is `category + target`; this VS Code resource uses `target = vscode`. " +
			"An empty `allowlist` blocks every extension and an empty `blocklist` allows every extension, so set `rules` deliberately.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier. Same value as `policy_id`.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"policy_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The unique identifier for this policy generated by StepSecurity.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The name of the policy.",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Optional human-readable description.",
			},
			"target": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(stepsecurityapi.DeveloperMDMTargetVSCode),
				MarkdownDescription: "IDE target for this policy. v1 supports only `vscode`.",
				Validators: []validator.String{
					stringvalidator.OneOf(stepsecurityapi.DeveloperMDMTargetVSCode),
				},
			},
			"mode": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "Policy mode. `allowlist` permits only the listed extensions and blocks everything else; " +
					"`blocklist` blocks the listed extensions and allows everything else.",
				Validators: []validator.String{
					stringvalidator.OneOf(stepsecurityapi.DeveloperMDMModeAllowlist, stepsecurityapi.DeveloperMDMModeBlocklist),
				},
			},
			"rules": schema.ListNestedAttribute{
				Required: true,
				MarkdownDescription: "Ordered list of allow/block rules. An empty list is valid but powerful: " +
					"empty `allowlist` blocks all extensions, empty `blocklist` allows all extensions.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"publisher": schema.StringAttribute{
							Required: true,
							MarkdownDescription: "VS Code marketplace publisher segment (e.g. `ms-python`). " +
								"No `*`, `.`, or spaces.",
							Validators: []validator.String{
								stringvalidator.LengthAtLeast(1),
							},
						},
						"name": schema.StringAttribute{
							Optional: true,
							MarkdownDescription: "VS Code extension name segment (e.g. `python`). " +
								"Omit to target the whole publisher. No `*` or spaces.",
						},
						"versions": schema.SetAttribute{
							ElementType: types.StringType,
							Optional:    true,
							MarkdownDescription: "Allowlist only. Requires `name`. Exact `major.minor.patch` versions, " +
								"with optional `@platform` suffix. Mutually exclusive with `stable`. " +
								"Do not use the literal `stable`; set `stable = true` instead.",
						},
						"stable": schema.BoolAttribute{
							Optional:            true,
							Computed:            true,
							Default:             booldefault.StaticBool(false),
							MarkdownDescription: "Allowlist only. Allow the extension's stable channel. Mutually exclusive with `versions`.",
						},
					},
				},
			},
			"created_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The user who created this policy.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The timestamp when this policy was created.",
			},
			"updated_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The user who last updated this policy.",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The timestamp when this policy was last updated.",
			},
		},
	}
}

// Configure adds the provider configured client to the resource.
func (r *developerMDMIDEExtensionPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(stepsecurityapi.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected stepsecurityapi.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

// ValidateConfig runs cross-field and cross-rule validation that schema validators cannot express.
func (r *developerMDMIDEExtensionPolicyResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var model developerMDMIDEExtensionPolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(validateDeveloperMDMIDEExtensionPolicy(ctx, model)...)
}

// Create creates the resource and sets the initial Terraform state.
func (r *developerMDMIDEExtensionPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan developerMDMIDEExtensionPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(validateDeveloperMDMIDEExtensionPolicy(ctx, plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiReq := buildDeveloperMDMIDEExtensionPolicyRequest(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	created, err := r.client.CreateDeveloperMDMPolicy(ctx, apiReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Developer MDM IDE extension policy",
			"Could not create policy, unexpected error: "+err.Error(),
		)
		return
	}

	applyDeveloperMDMPolicyToModel(ctx, created, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read refreshes the Terraform state with the latest data.
func (r *developerMDMIDEExtensionPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state developerMDMIDEExtensionPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	policy, err := r.client.GetDeveloperMDMPolicy(ctx, state.PolicyID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading Developer MDM IDE extension policy",
			"Could not read policy ID "+state.PolicyID.ValueString()+": "+err.Error(),
		)
		return
	}

	applyDeveloperMDMPolicyToModel(ctx, policy, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *developerMDMIDEExtensionPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan developerMDMIDEExtensionPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(validateDeveloperMDMIDEExtensionPolicy(ctx, plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiReq := buildDeveloperMDMIDEExtensionPolicyRequest(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	updated, err := r.client.UpdateDeveloperMDMPolicy(ctx, plan.PolicyID.ValueString(), apiReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating Developer MDM IDE extension policy",
			"Could not update policy, unexpected error: "+err.Error(),
		)
		return
	}

	applyDeveloperMDMPolicyToModel(ctx, updated, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *developerMDMIDEExtensionPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state developerMDMIDEExtensionPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteDeveloperMDMPolicy(ctx, state.PolicyID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error deleting Developer MDM IDE extension policy",
			"Could not delete policy, unexpected error: "+err.Error(),
		)
		return
	}
}

// ImportState imports the resource by backend policy_id and lets Read populate the rest.
func (r *developerMDMIDEExtensionPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("policy_id"), req, resp)
}

// validateDeveloperMDMIDEExtensionPolicy enforces field, cross-field, and cross-rule rules
// that mirror the backend. It is called from ValidateConfig and from create/update builders.
func validateDeveloperMDMIDEExtensionPolicy(ctx context.Context, model developerMDMIDEExtensionPolicyModel) diag.Diagnostics {
	var diags diag.Diagnostics

	isBlocklist := model.Mode.ValueString() == stepsecurityapi.DeveloperMDMModeBlocklist

	// Track compiled key (publisher + name) to reject mixing stable and explicit versions.
	type keyState struct{ stable, versions bool }
	states := map[string]*keyState{}

	for idx, rule := range model.Rules {
		rulePath := path.Root("rules").AtListIndex(idx)

		publisher := rule.Publisher.ValueString()
		if !rule.Publisher.IsUnknown() && !developerMDMIdentifierRegex.MatchString(publisher) {
			diags.AddAttributeError(
				rulePath.AtName("publisher"),
				"Invalid publisher",
				fmt.Sprintf("Publisher %q must match %s (no '*', '.', or spaces).", publisher, developerMDMIdentifierPattern),
			)
		}

		hasName := !rule.Name.IsNull() && !rule.Name.IsUnknown() && rule.Name.ValueString() != ""
		name := rule.Name.ValueString()
		if hasName && !developerMDMIdentifierRegex.MatchString(name) {
			diags.AddAttributeError(
				rulePath.AtName("name"),
				"Invalid extension name",
				fmt.Sprintf("Name %q must match %s (no '*' or spaces).", name, developerMDMIdentifierPattern),
			)
		}

		var versions []string
		if !rule.Versions.IsNull() && !rule.Versions.IsUnknown() {
			diags.Append(rule.Versions.ElementsAs(ctx, &versions, false)...)
		}
		hasVersions := len(versions) > 0
		stable := rule.Stable.ValueBool()

		if isBlocklist {
			if hasVersions {
				diags.AddAttributeError(
					rulePath.AtName("versions"),
					"Versions not allowed on a blocklist",
					"`versions` is allowlist-only. Remove versions from blocklist rules.",
				)
			}
			if stable {
				diags.AddAttributeError(
					rulePath.AtName("stable"),
					"stable not allowed on a blocklist",
					"`stable` is allowlist-only. Remove `stable = true` from blocklist rules.",
				)
			}
		} else {
			if hasVersions && !hasName {
				diags.AddAttributeError(
					rulePath.AtName("versions"),
					"versions require name",
					"`versions` can only be set on a rule that also sets `name`.",
				)
			}
			if stable && hasVersions {
				diags.AddAttributeError(
					rulePath.AtName("stable"),
					"stable and versions are mutually exclusive",
					"A rule may set `stable = true` or `versions`, not both.",
				)
			}
			for _, v := range versions {
				if v == "stable" {
					diags.AddAttributeError(
						rulePath.AtName("versions"),
						"Literal version \"stable\" is not allowed",
						"Set `stable = true` instead of listing the literal version \"stable\".",
					)
					continue
				}
				if !developerMDMVersionRegex.MatchString(v) {
					diags.AddAttributeError(
						rulePath.AtName("versions"),
						"Invalid version",
						fmt.Sprintf("Version %q must be major.minor.patch with an optional @platform suffix.", v),
					)
				}
			}
		}

		key := publisher + "\x00" + name
		st := states[key]
		if st == nil {
			st = &keyState{}
			states[key] = st
		}
		if stable {
			st.stable = true
		}
		if hasVersions {
			st.versions = true
		}
		if st.stable && st.versions {
			diags.AddError(
				"Conflicting rules for the same extension",
				fmt.Sprintf("Extension %q cannot mix `stable` and explicit `versions` across rules.", key),
			)
		}
	}

	return diags
}

// buildDeveloperMDMIDEExtensionPolicyRequest converts the model into an API request body.
func buildDeveloperMDMIDEExtensionPolicyRequest(ctx context.Context, model developerMDMIDEExtensionPolicyModel, diags *diag.Diagnostics) stepsecurityapi.DeveloperMDMPolicyRequest {
	rules := make([]stepsecurityapi.DeveloperMDMIDEExtensionRule, 0, len(model.Rules))
	for _, r := range model.Rules {
		rule := stepsecurityapi.DeveloperMDMIDEExtensionRule{
			Publisher: r.Publisher.ValueString(),
			Name:      r.Name.ValueString(),
			Versions:  sortedStringSet(ctx, r.Versions, diags),
			Stable:    r.Stable.ValueBool(),
		}
		rules = append(rules, rule)
	}

	spec := stepsecurityapi.DeveloperMDMIDEExtensionSpec{Rules: rules}
	specJSON, err := json.Marshal(spec)
	if err != nil {
		diags.AddError("Failed to encode policy spec", err.Error())
	}

	return stepsecurityapi.DeveloperMDMPolicyRequest{
		Name:        model.Name.ValueString(),
		Description: model.Description.ValueString(),
		Category:    stepsecurityapi.DeveloperMDMCategoryIDEExtension,
		Target:      developerMDMPolicyTarget(model.Target),
		SpecVersion: stepsecurityapi.DeveloperMDMSpecVersionIDEExtension,
		Mode:        model.Mode.ValueString(),
		Spec:        specJSON,
	}
}

func developerMDMPolicyTarget(target types.String) string {
	if target.IsNull() || target.IsUnknown() || target.ValueString() == "" {
		return stepsecurityapi.DeveloperMDMTargetVSCode
	}
	return target.ValueString()
}

// sortedStringSet converts a set into a deterministically sorted slice to avoid spurious diffs.
func sortedStringSet(ctx context.Context, set types.Set, diags *diag.Diagnostics) []string {
	if set.IsNull() || set.IsUnknown() {
		return nil
	}
	var values []string
	diags.Append(set.ElementsAs(ctx, &values, false)...)
	sort.Strings(values)
	return values
}

// applyDeveloperMDMPolicyToModel applies an API policy response into the Terraform model.
// It rejects policies whose category is not ide_extension because this resource cannot manage them.
func applyDeveloperMDMPolicyToModel(ctx context.Context, policy *stepsecurityapi.DeveloperMDMPolicy, model *developerMDMIDEExtensionPolicyModel, diags *diag.Diagnostics) {
	if policy.Category != stepsecurityapi.DeveloperMDMCategoryIDEExtension {
		diags.AddError(
			"Unsupported Developer MDM policy category",
			fmt.Sprintf(
				"Policy %q has category %q, but stepsecurity_developer_mdm_ide_extension_policy only manages %q policies.",
				policy.PolicyID, policy.Category, stepsecurityapi.DeveloperMDMCategoryIDEExtension,
			),
		)
		return
	}

	model.ID = types.StringValue(policy.PolicyID)
	model.PolicyID = types.StringValue(policy.PolicyID)
	model.Name = types.StringValue(policy.Name)
	target := policy.Target
	if target == "" {
		target = stepsecurityapi.DeveloperMDMTargetVSCode
	}
	model.Target = types.StringValue(target)
	model.Mode = types.StringValue(policy.Mode)
	model.CreatedBy = types.StringValue(policy.CreatedBy)
	model.CreatedAt = types.StringValue(policy.CreatedAt)
	model.UpdatedBy = types.StringValue(policy.UpdatedBy)
	model.UpdatedAt = types.StringValue(policy.UpdatedAt)

	if policy.Description != "" {
		model.Description = types.StringValue(policy.Description)
	} else {
		model.Description = types.StringNull()
	}

	var spec stepsecurityapi.DeveloperMDMIDEExtensionSpec
	if len(policy.Spec) > 0 {
		if err := json.Unmarshal(policy.Spec, &spec); err != nil {
			diags.AddError("Failed to decode policy spec", err.Error())
			return
		}
	}

	rules := make([]developerMDMIDEExtensionRuleModel, 0, len(spec.Rules))
	for _, r := range spec.Rules {
		rule := developerMDMIDEExtensionRuleModel{
			Publisher: types.StringValue(r.Publisher),
			Stable:    types.BoolValue(r.Stable),
		}
		if r.Name != "" {
			rule.Name = types.StringValue(r.Name)
		} else {
			rule.Name = types.StringNull()
		}
		if len(r.Versions) > 0 {
			versionValues := make([]attr.Value, len(r.Versions))
			for i, v := range r.Versions {
				versionValues[i] = types.StringValue(v)
			}
			setValue, setDiags := types.SetValue(types.StringType, versionValues)
			diags.Append(setDiags...)
			rule.Versions = setValue
		} else {
			rule.Versions = types.SetNull(types.StringType)
		}
		rules = append(rules, rule)
	}
	model.Rules = rules
}
